version: '3.8'
services:
  bko:
    build:
      context: ../../
      dockerfile: devops/Dockerfiles/bko.dockerfile
    ports:
      - "17803:80"
    restart: always
    networks:
      - uluars

volumes:
  new_admin_bkomongodb_data:


networks:
  uluars:

    #3
